server:
  port: 8080
  servlet:
    session:
      timeout: 1000
      cookie:
        max-age: 1000
        name: SID
        http-only: true
#        secure: true
  
spring:
  config:
    activate:
      on-profile: local
      
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    
  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate-ddl: false
        open-in-view: false
        ddl-auto: none
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    view:
      prefix: classpath:templates/
      suffix: html
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    user:
      name: admin
      password: admin
  
  datasource:
    test-db:
      #compile group: 'org.bgee.log4jdbc-log4j2', name: 'log4jdbc-log4j2-jdbc4.1', version: '1.16'
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:log4jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
      username: eggseller
      password: ENC(tWGo680FO0RVhQ83l79W/Q==)
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        pool-name: pool-eggseller
    eggseller-db:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: eggseller
      password: ENC(gMlOZzl7kg2m6pouK567kmo1Jp93WBmh)
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50
        transaction-isolation: TRANSACTION_SEREALIZBLE
        pool-name: pool-eggseller
    test-db-postgre:
      driver-class-name: org.postgresql.ds.PGSimpleDataSource
      jdbc-url: "jdbc:postgresql://localhost:5432/test"
      username: postgres
      password: ENC(gMlOZzl7kg2m6pouK567kmo1Jp93WBmh)
    
---
spring:
  config:
    activate:
      on-profile: dev

      
#mybatis:
##  mapper-locations: classpath:mappers/**/*.xml
#  type-aliases-package: com.eggseller.test.model
#  configuration:
#    lazyLoadingEnabled: true
#    aggressiveLazyLoading: false
#    mapUnderscoreToCamelCase: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml

logging:
  level:
    root: error
    '[com.eggseller.test]': debug

      
