server:
  port: 8080
  servlet:
    session:
      timeout: 1000
      cookie:
        max-age: 1000
        name: SID
        http-only: true
#        secure: true
  
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true

  mvc:
    view:
      prefix: classpath:templates/
      suffix: html
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    user:
      name: admin
      password: admin
    
  datasource:
    test-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
      username: eggseller
      password: ENC(tWGo680FO0RVhQ83l79W/Q==)
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        pool-name: pool-eggseller
    eggseller-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost/eggseller?autoReconnect=true&serverTimezone=UTC"
      username: eggseller
      password: ENC(tWGo680FO0RVhQ83l79W/Q==)
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50
        transaction-isolation: TRANSACTION_SEREALIZBLE
        pool-name: pool-eggseller
    test-db-postgre:
      driver-class-name: org.postgresql.ds.PGSimpleDataSource
      jdbc-url: "jdbc:postgresql://localhost:5432/test"
      username: postgres
      password: ENC(tWGo680FO0RVhQ83l79W/Q==)

mybatis:
#  mapper-locations: classpath:mappers/**/*.xml
#  type-aliases-package: com.eggseller.test.model
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true

swagger:
  apiinfo:
    title: aaaaaaa
    description: ccccccc
    version: 1.0.0    

  
logging:
  level:
    root: error
    '[com.eggseller.test]': debug